GPAK: gpak_fopen
gpak_add_directory
gpak_add_file
gpak_close
gpak_fclose
gpak_feof
gpak_fgetc
gpak_fgets
gpak_find_directory
gpak_find_file
gpak_fopen
gpak_fread
gpak_fseek
gpak_ftell
gpak_get_root
gpak_open
gpak_set_compression_algorithm
gpak_set_compression_level
gpak_set_error_handler
gpak_set_process_handler
gpak_set_user_data
gpak_ungetc
gpak_fopen()
GPAK_API gpak_file_t* gpak_fopen (gpak_t * _pak, const char * _path)
Brief Description:\n Opens a file in a G-PAK archive.
This function opens a file with the specified _path in the G-PAK archive.
Parameters
_pak A pointer to the gpak_t.
_path A string containing the path of the file to open.
Returns
A pointer to the opened gpak_file_t or NULL if an error occurred.
Definition at line 372 of file gpak.c.
 {
     filesystem_tree_file_t* _file_info = filesystem_tree_find_file(_pak->root_, _path);
     if (!_file_info)
     {
         _gpak_make_error(_pak, GPAK_ERROR_FILE_NOT_FOUND);
         return NULL;
     }
     _pak->current_file_ = filesystem_tree_file_path(_pak->root_, _file_info);
     uint32_t uncompressed_size = _file_info->entry_.uncompressed_size_;
     uint32_t compressed_size = _file_info->entry_.compressed_size_;
     gpak_file_t* mfile = (gpak_file_t*)malloc(sizeof(gpak_file_t));
     mfile->data_ = (char*)malloc(uncompressed_size + 1);
     mfile->data_[uncompressed_size] = '\0';
     mfile->stream_ = fmemopen(mfile->data_, uncompressed_size, "wb+");
     // Setting position to file start
     fseek(_pak->stream_, _file_info->entry_.offset_, SEEK_SET);
     if (_pak->header_.compression_ & GPAK_HEADER_COMPRESSION_DEFLATE)
         mfile->crc32_ = _gpak_decompressor_inflate(_pak, _pak->stream_, mfile->stream_, compressed_size);
     else if (_pak->header_.compression_ & GPAK_HEADER_COMPRESSION_LZ4)
         mfile->crc32_ = _gpak_decompressor_lz4(_pak, _pak->stream_, mfile->stream_, compressed_size);
     else if (_pak->header_.compression_ & GPAK_HEADER_COMPRESSION_ZST)
         mfile->crc32_ = _gpak_decompressor_zstd(_pak, _pak->stream_, mfile->stream_, compressed_size);
     else
         mfile->crc32_ = _gpak_decompressor_none(_pak, _pak->stream_, mfile->stream_, compressed_size);
     fseek(mfile->stream_, 0, SEEK_SET);
     // Check crc32
     if (mfile->crc32_ != _file_info->entry_.crc32_)
     {
         _gpak_make_error(_pak, GPAK_ERROR_FILE_CRC_NOT_MATCH);
         free(_pak->current_file_);
         gpak_fclose(mfile);
         return NULL;
     }
     free(_pak->current_file_);
     return mfile;
 }
References _gpak_decompressor_inflate(), _gpak_decompressor_lz4(), _gpak_decompressor_none(), _gpak_decompressor_zstd(), gpak_entry_header::compressed_size_, gpak_header::compression_, gpak_entry_header::crc32_, gpak_file::crc32_, gpak::current_file_, gpak_file::data_, filesystem_tree_file::entry_, filesystem_tree_file_path(), filesystem_tree_find_file(), GPAK_ERROR_FILE_CRC_NOT_MATCH, GPAK_ERROR_FILE_NOT_FOUND, gpak_fclose(), GPAK_HEADER_COMPRESSION_DEFLATE, GPAK_HEADER_COMPRESSION_LZ4, GPAK_HEADER_COMPRESSION_ZST, gpak::header_, gpak_entry_header::offset_, gpak::root_, gpak::stream_, gpak_file::stream_, and gpak_entry_header::uncompressed_size_.