GPAK: gpak_close
gpak_add_directory
gpak_add_file
gpak_close
gpak_fclose
gpak_feof
gpak_fgetc
gpak_fgets
gpak_find_directory
gpak_find_file
gpak_fopen
gpak_fread
gpak_fseek
gpak_ftell
gpak_get_root
gpak_open
gpak_set_compression_algorithm
gpak_set_compression_level
gpak_set_error_handler
gpak_set_process_handler
gpak_set_user_data
gpak_ungetc
gpak_close()
GPAK_API int gpak_close (gpak_t * _pak)
Brief Description:\n Closes a G-PAK archive.
This function closes the specified G-PAK archive and deallocates any associated resources.
Parameters
_pak A pointer to the gpak_t to close.
Returns
An integer value indicating success (0) or failure (-1).
Definition at line 290 of file gpak.c.
 {
     if (_pak != NULL)
     {
         if (_pak->stream_ != NULL)
         {
             // Recalculate header
             if ((_pak->mode_ & GPAK_MODE_CREATE) || (_pak->mode_ & GPAK_MODE_UPDATE))
             {
                 if (_pak->mode_ & GPAK_MODE_CREATE)
                 {
                     if (_pak->header_.compression_ & GPAK_HEADER_COMPRESSION_ZST)
                         _gpak_compressor_generate_dictionary(_pak);
                 }
                 _gpak_archivate_file_tree(_pak);
             }
             filesystem_tree_delete(_pak->root_);
             _update_pak_header(_pak);
             fclose(_pak->stream_);
         }
         free(_pak->dictionary_);
         free(_pak);
         return _gpak_make_error(_pak, GPAK_ERROR_OK);
     }
     return -1;
 }
References _gpak_compressor_generate_dictionary(), gpak_header::compression_, gpak::dictionary_, filesystem_tree_delete(), GPAK_ERROR_OK, GPAK_HEADER_COMPRESSION_ZST, GPAK_MODE_CREATE, GPAK_MODE_UPDATE, gpak::header_, gpak::mode_, gpak::root_, and gpak::stream_.
Referenced by gpak_open().