GPAK: _gpak_compressor_generate_dictionary
_gpak_compressor_deflate
_gpak_compressor_generate_dictionary
_gpak_compressor_lz4
_gpak_compressor_none
_gpak_compressor_zstd
_gpak_decompressor_inflate
_gpak_decompressor_lz4
_gpak_decompressor_none
_gpak_decompressor_zstd
_gpak_compressor_generate_dictionary()
GPAK_API int32_t _gpak_compressor_generate_dictionary (gpak_t * _pak)
Brief Description:\n Generates a compression dictionary for the specified G-PAK archive.
This function generates a compression dictionary for the specified G-PAK archive, which can be used to improve the compression ratio for certain algorithms.
Parameters
_pak A pointer to the gpak_t.
Returns
A non-negative value if the dictionary generation is successful, or a negative value if an error occurred.
Definition at line 474 of file gpak_compressors.c.
 {
     char* samples = NULL;
     size_t sample_sizes[_DICTIONARY_SAMPLE_COUNT];
     size_t samples_count = 0ull;
     size_t samples_capacity = 0ull;
     size_t current_offset = 0ull;
     filesystem_tree_iterator_t* iterator = filesystem_iterator_create(_pak->root_);
     filesystem_tree_node_t* next_directory = _pak->root_;
     do
     {
         if (samples_count >= _DICTIONARY_SAMPLE_COUNT - 1)
             break;
         filesystem_tree_file_t* next_file = NULL;
         while ((next_file = filesystem_iterator_next_file(iterator)))
         {
             FILE* _infile = fopen(next_file->path_, "rb");
             fseek(_infile, 0, SEEK_END);
             sample_sizes[samples_count] = ftell(_infile);
             fseek(_infile, 0, SEEK_SET);
             samples_capacity += sample_sizes[samples_count];
             samples = (char*)realloc(samples, samples_capacity);
             _freadb(samples + current_offset, 1ull, sample_sizes[samples_count], _infile);
             current_offset += sample_sizes[samples_count];
             fclose(_infile);
             if (samples_count >= _DICTIONARY_SAMPLE_COUNT - 1)
                 break;
             ++samples_count;
         }
     } while ((next_directory = filesystem_iterator_next_directory(iterator)));
     filesystem_iterator_free(iterator);
     size_t average_file_size = 0ull;
     for (size_t idx = 0ull; idx < samples_count; ++idx)
         average_file_size += sample_sizes[idx] / samples_count;
     size_t nearest_pow_of_2 = 1;
     while (nearest_pow_of_2 < average_file_size)
         nearest_pow_of_2 *= 2;
     _pak->header_.dictionary_size_ = nearest_pow_of_2;
     _pak->dictionary_ = (char*)malloc(_pak->header_.dictionary_size_);
     _pak->header_.dictionary_size_ = ZDICT_trainFromBuffer(_pak->dictionary_, _pak->header_.dictionary_size_, samples, sample_sizes, samples_count);
     _pak->dictionary_ = (char*)realloc(_pak->dictionary_, _pak->header_.dictionary_size_);
     fseek(_pak->stream_, sizeof(pak_header_t), SEEK_SET);
     _fwriteb(_pak->dictionary_, 1ull, _pak->header_.dictionary_size_, _pak->stream_);
     free(samples);
     return _gpak_make_error(_pak, GPAK_ERROR_OK);
 }
References gpak::dictionary_, gpak_header::dictionary_size_, filesystem_iterator_create(), filesystem_iterator_free(), filesystem_iterator_next_directory(), filesystem_iterator_next_file(), GPAK_ERROR_OK, gpak::header_, filesystem_tree_file::path_, gpak::root_, and gpak::stream_.
Referenced by gpak_close().